### ISSUE TITLE
关于扫描和绑定设备

### ISSUE THREAD

**Issue by liduojun** [MiEcosystem/ios-mijia-sdk#4]
你好，我们设备是蓝牙和wifi双模块设备，在扫描时用该库的蓝牙扫描方法 MHBluetoothDiscovery 提供的startSearch方法进行扫描，用MHXiaoMiConnectManager 提供的registerXiaoMiBluetoothDeviceWith 和 loginXiaoMiBluetoothDeviceWith 提供的方法连接显示报错  
![401535374248_ pic_hd](https://user-images.githubusercontent.com/18310467/44696925-295f2c00-aaac-11e8-9008-eeded56297ab.jpg) 绑定失败于状态3，用wifi 功能  这个类 MHDeviceManager 提供的bindDeviceWith绑定设备方法也报错，显示不存在该设备。我应该用哪个api调用，谢谢，请回复我该怎么继续，
还有一个疑问，安卓的sdk调用时有自带的米家连接绑定设备界面，请问iOS这边是否有提供，谢谢？

**Comment by chundong** [comment]
你好，你用的应该是独立sdk，如果你想快联设备，需要使用combo快联的方式，具体使用方法见 
[独立SDK的combo快联文档 3.4 章节](https://github.com/MiEcosystem/ios-mijia-sdk/blob/master/MiHomeBluetoothAPI.md#34-combo%E5%BF%AB%E8%81%94)

**Comment by liduojun** [comment]
你好，我按照你说的combo快联方式连接时遇到了新的问题，这个方法确实可行，但是需要一个uid，用户的userid是在请求地址: https://open.account.xiaomi.com/user/profile这个接口中获取的，我在官网申请的应用是在6月1日之后申请的，官网说明是6.1之后申请的应用请求这个接口只返回 unionId，不返回userid，所以我用unionId绑定时出错，把uid手动写成我的小米id，是绑定成功的，请问怎么解决？谢谢

**Comment by chundong** [comment]
MHAccount 有一个 fetchAccountProfile的方法，可以获取当前账户相关的信息 MHAccountProfile, MHAccountProfile 中的userId 就是当前用户登录的userId。调用的方式为
```objc
//MHAccount 初始化
_account = [[MHAccount alloc] initWithAppId:@"appId" redirectUrl:@"回调网址"];

....
//添加notification
[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(accountLogin:) name:MH_Account_Login_Sucess object:nil];

//MHAccount 登录
[_account login:@[@1,@3,@6000]];

.....

//登录成功会有一个notification。在notification中调用
- (void) accountLogin:(id)motif {
     [_account fetchAccountProfile:^(MHAccountProfile *profile, NSError *error) {
        _profile = profile;
       NSLog(@"_profile.userId = %@", _profile.userId);
    }];
}

```

**Comment by liduojun** [comment]
你好，我们也用过这个方法，一样也是不返回userid，为null。问题是小米开放平台规则改了，新建的应用都不返回userId，只返回unionId。

**Comment by chundong** [comment]
开放平台的这个改动并没有通知到我们，所以这个问题我找小米开放平台的人了解一下，看要求是需要更新sdk才成。

**Comment by chundong** [comment]
@liduojun 麻烦你们联系一下与你们对接的米家产品经理，提供一下appId信息，我们会统一帮你们开权限的

**Comment by chundong** [comment]
@liduojun 权限已经开通，麻烦确认一下
