### ISSUE TITLE
Mijia SDK中包含"App-prefs"私有API的使用，被App Store拒绝上架

### ISSUE THREAD

**Issue by fosen** [MiEcosystem/ios-mijia-sdk#5]
MiHomeSDK的版本信息如下：VersionString是 PROGRAM:MiHomeSDK  PROJECT:MiHomeSDK-1

请提供一版此SDK版本的修改后的包，收件邮箱：guobo@ihealthlabs.com.cn

**Comment by chundong** [comment]
你好，你现在用的是MiHomeSDK.framework，在app store审核中被检查出 prefs:root=WIFI 的跳转吗？

**Comment by chundong** [comment]
@fosen 我基于MiHomeSDK.framework 做了一些修改，如果想下载这个SDK，请跟对应的米家产品经理要下载地址。 MiHomeSDK 现在是老的SDK，不在做维护了。

**Comment by fosen** [comment]
@chundong  现在地址发到邮箱，可以吗？guobo@ihealthlabs.com.cn 新版的SDK与老版的SDK差别大吗？差别大的话，能否在老版基础上改一次。多谢
